### ISSUE TITLE
how to remove the underline of the text inside the tagview

### ISSUE THREAD

**Issue by ashokslsk** [2dxgujun/AndroidTagGroup#32]
Hi awesome library but how to remove the underline of the text inside the tagview.

**Comment by minhle2994** [comment]
Same question, may be the issue come from different version of android :(

**Comment by ferrytan** [comment]
i also came across this problem, fixed by adding .clearComposingText() on the TagView after appendTag()

**Comment by rajeevjaiswal** [comment]
yes same issue

**Comment by SufianBabri** [comment]
I imported the library as module and commented out the `setOnKeyListener()` line. That red line is not showing anymore. Since I'm only showing tags for now, it works for me fine.

**Edit**
It seems that it broke after few rotations. I now added this method to `TagView`:

    @Override
    protected boolean getDefaultEditable() {
        return false;
    }

**Comment by ravi123shanker** [comment]
Same issue with me any solution?

**Comment by SufianBabri** [comment]
@ravi123shanker make the changes I posted in my previous comment, and it will fix the issue. :)

**Comment by ravi123shanker** [comment]
@SufianBabri thanks for your reply now it is working.

**Comment by srujanb** [comment]
@SufianBabri  and @ravi123shanker  is that "return false" solution working without any error? If yes, I will adopt it.

**Comment by ravi123shanker** [comment]
@srujan7 Yes, simply "return false" from getDefaultEditable(). it will resolve your issue.
       @Override
        protected boolean getDefaultEditable() {
            return false;
        }

**Comment by srujanb** [comment]
@ravi123shanker It is crashing my app. I guess it works only if you are not using `appendMode`.

**Comment by SufianBabri** [comment]
@srujan7 please share your LogCat.

**Comment by srujanb** [comment]
@SufianBabri 

Here is my log cat: 

    E/UncaughtException: java.lang.NullPointerException
                                                                                    at android.view.inputmethod.InputConnectionWrapper.finishComposingText(InputConnectionWrapper.java:78)
                                                                                    at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:355)
                                                                                    at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:77)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                    at android.os.Looper.loop(Looper.java:213)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5225)
                                                                                    at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                    at java.lang.reflect.Method.invoke(Method.java:525)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:741)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
                                                                                    at dalvik.system.NativeStart.main(Native Method)
    02-13 14:47:07.797 842-846/? E/Diag_Lib: [IMS_FATAL]| 251 | 846 |qvp_rtp_handle_signals iRet : 0
    02-13 14:47:07.797 842-846/? E/Diag_Lib: [IMS_FATAL]| 238 | 846 |qvp_rtp_handle_signals     qpDplMainLoop: Calling imsSignalHandler
    02-13 14:47:07.797 842-846/? E/Diag_Lib: [IMS_FATAL]| 155 | 846 |qpdpl:imsSignalHandler: GLobal data NULL or Event list size is 0
    02-13 14:47:07.797 842-846/? E/Diag_Lib: [IMS_FATAL]| 243 | 846 |qvp_rtp_handle_signals add read fd : 9
    02-13 14:47:07.817 20104-20104/spoonmoon.com.msimplinksv21 E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             java.lang.NullPointerException
                                                                                 at android.view.inputmethod.InputConnectionWrapper.finishComposingText(InputConnectionWrapper.java:78)
                                                                                 at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:355)
                                                                                 at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:77)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                 at android.os.Looper.loop(Looper.java:213)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5225)
                                                                                 at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:525)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:741)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
                                                                                 at dalvik.system.NativeStart.main(Native Method)


It happens only while displaying `tagGroups` that have the `inputTag` available.

**Comment by SufianBabri** [comment]
@srujan7 try [this fork][1] which is also active. If the problem isn't fixed, please file an issue in THAT repo and also post the issue link here (just so we know as well).

  [1]: https://github.com/Eddydpyl/AndroidTagGroup

**Comment by nuhkoca** [comment]
Hi all,

Where should I put that code block?

**Comment by royherma** [comment]
help??
